### ISSUE TITLE
"The given data failed to pass validation." when calling the certificate function

### ISSUE THREAD

**Issue by jonassiewertsen** [ohdearapp/ohdear-php-sdk#11]
I am regulary getting the following error, when calling `certificateHealth()`

<img width="1012" alt="Screen Shot 2020-03-03 at 23 12 09" src="https://user-images.githubusercontent.com/38906163/75925140-70c83480-5e68-11ea-8058-ffc4fde7ac7b.png">

It does happening when calling something like this:
```php

$ohDear->site($siteId)->certificateHealth();
```

Everything is working as expected. After calling the rout a few times, the error occurres. Waiting a little and everything does go back to normal for a while.

**Comment by mattiasgeniar** [comment]
Hi @jonassiewertsen!

I just shipped an update to our API that should resolve this, the problem was we could return a `pending` certificate health check - in which case the check isn't executed yet and the `unserialize()` would fail.

The API will now only return successfully executed certificate health checks.

If the error keeps re-occuring, could you reply here? I'll reopen the issue then for further troubleshooting.

Thanks for the heads-up!

M.
